//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.26 at 04:09:20 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://springws.javaclickonline.blogspot.com/MoviesBrowser/schemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.blogspot.javaclickonline.springws.moviesbrowser;
